version: '3'

services:
  app:
    build: .
    depends_on:
      - db
      - redis
    command: npm run dev
    ports:
      - "4000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/bcrypt/
    env_file:
      - ./database/.env
    environment:
      - PORT=3000
      - GOOGLE_API_KEY=AIzaSyBMs9PzMrbSGJrhIIqJBZ7YZxkSDzgJuBM
      - CLOUDINARY_KEY=922219989176362
      - CLOUDINARY_NAME=tuanrumah
      - CLOUDINARY_SECRET=V_SscHXLgFFcZGhiFpotDiCOui4
      - EXPRESS_SESSION_SECRET=FakTPJTRYVdX2UU12HMFoXSFX4NwWp3uHRveUlEI
      - TELEGRAM_API_KEY=1394882290:AAFzZmxQ3TlXCTfg10kVADykcsCp7E4Tl1w
  
  db:
    image: "mysql:8.0.15"
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./database/.env
    ports:
      - "3307:3306"

  mongo:
    image: mongo:4.4.1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: billion_dollar_app
  
  redis:
    image: redis:alpine

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
    